language: erlang
script: make test
otp_release:
  - R15B01
# Older versions disabled for now. System test fails (all test are
# skipped, doesn't happen when run interactively), needs further
# investigation.
# - R15B
# - R14B04
# - R14B03
# - R14B02
